### ISSUE TITLE
Use Kauai Labs' official Maven repository

### ISSUE THREAD

**Issue by RobinsonZ** [wpilibsuite/GradleRIO#112]
Per [this page](https://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/), there's an official Kauai Labs Maven repository at http://www.kauailabs.com/maven2 with the NavX artifact (at least for Java) at `com.kauailabs.navx.frc:navx_frc`. Probably would be good to use that instead of the OpenRIO mirror.

**Comment by edelmanjm** [comment]
y tho

**Comment by JacisNonsense** [comment]
We were working on switching to KL's official repo earlier this year, however since C++ releases weren't published, we didn't want to create a possible disparity between Java and C++ release schedules.

We're working on changing this for 2019.

**Comment by JacisNonsense** [comment]
Closed since this is a vendor library issue now (we no longer package NavX and CTRE releases, they are added by including a `.json` file in your project directory, which is managed by VSCode / can be done very easily manually)
