### ISSUE TITLE
Use DS connection as another method to detect the roboRIO

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/GradleRIO#123]
Last year for eclipse we used the DS IP connection as another method to attempt to find the roboRIO, and it was very helpful in a lot of scenarios. We should add this to GradleRIO. The code can be found in multiple places in the wpilibsuite org.

**Comment by PeterJohnson** [comment]
https://github.com/wpilibsuite/riolog/blob/master/src/main/java/netconsole2/RioConnector.java

https://github.com/wpilibsuite/roborio-ant-tasks/blob/master/src/main/java/edu/wpi/first/ant/FindRoborioTask.java

**Comment by JacisNonsense** [comment]
Close in 3b0b0b6
