### ISSUE TITLE
Docs being bundled in the jar

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/GradleRIO#133]
For some reason java docs are being bundled in the jar sent to the roborio.  We should not do this because it just increases deploy size.

**Comment by AustinShalit** [comment]
Actually this is probably an issue with the jar kauai is posting

**Comment by ThadHouse** [comment]
We just copy in whatever is in any jars that are libraries, so if their jar includes them, and those are the only ones there, its a problem in their libraries and we can close this issue.

**Comment by JacisNonsense** [comment]
This doesn't seem like our issue - filtering jar contents isn't a region I'd like to play in
