### ISSUE TITLE
IntelliJ Idea doesn't recognize grade?

### ISSUE THREAD

**Issue by GaganBhat** [wpilibsuite/GradleRIO#134]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/25236969/43372599-0ef659a2-9368-11e8-95bd-045edcbab625.png">

Looks like IntelliJ doesn't recognize the file system as a grade project even though I specifically clicked on build.gradle when importing.

I followed and replicated the exact same steps on a windows computer and didn't run into this issue.

**Comment by edelmanjm** [comment]
Did you initially import the project as a Gradle project or add it after the fact?

**Comment by GaganBhat** [comment]
@edelmanjm sorry for the lack of description, didn't think that the enter button would post the issue instantly. I imported the project from the welcome screen, and it recognized it as a grade project, I checked auto import, and finish.

**Comment by edelmanjm** [comment]
Can you post your project structure?

**Comment by GaganBhat** [comment]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/25236969/43372632-849893d2-9368-11e8-87f4-7d73881b6ede.png">

Here's the structure.

**Comment by GaganBhat** [comment]
`
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Failed to create parent directory '/Users/chandana.bhat@in.ibm.com/Documents/Programming/Java/FRC/Basebot-Code/.gradle/4.4' when creating directory '/Users/chandana.bhat@in.ibm.com/Documents/Programming/Java/FRC/Basebot-Code/.gradle/4.4/fileHashes'
`

I also get the above error when I try to refresh gradle by clicking on the sync button. 
<img width="150" alt="image" src="https://user-images.githubusercontent.com/25236969/43372695-0b3f8102-9369-11e8-96ff-70a330585eae.png">

**Comment by JacisNonsense** [comment]
Your gradle version is well out of date. Update to 4.9 and try again

**Comment by GaganBhat** [comment]
Alright, it was previously not using the local gradle install, so I did that now. Here's the error I am getting now. 

```

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
/Users/chandana.bhat@in.ibm.com/Documents/Programming/Java/FRC/Basebot-Code/.gradle/4.9/fileHashes/fileHashes.lock (Permission denied)
```

**Comment by GaganBhat** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/25236969/43372970-2569ea92-936c-11e8-821a-eaae30d544eb.png">

Another weird thing is that it builds the project if I run it from the terminal. But doesn't work with IntelliJ.

**Comment by GaganBhat** [comment]
I just imported it into my windows machine, everything works perfectly. 
![image](https://user-images.githubusercontent.com/25236969/43373799-a322ed08-9371-11e8-8cff-2688dc5da53d.png)

**Comment by JacisNonsense** [comment]
You should definitely not run gradle as root. chown ~/.gradle, projectdir/gradle and projectdir/.gradle for your current user

**Comment by JacisNonsense** [comment]
Run `./gradlew --version` and send me the output. You may have to update your JDK

**Comment by GaganBhat** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/25236969/43374755-ec55cd92-9376-11e8-8da5-1cce15342188.png">

**Comment by JacisNonsense** [comment]
`--version`, not `version`

**Comment by GaganBhat** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/25236969/43374910-a4a7972c-9377-11e8-9a7b-2ddba1ca56bd.png">

**Comment by GaganBhat** [comment]
Alright, I updated project pref. to 1.8  and looks like it build successfully. Thanks for the help!
