### ISSUE TITLE
Support For frc2019-toolchain

### ISSUE THREAD

**Issue by jath03** [wpilibsuite/GradleRIO#143]
I'm using the [beta ppa](https://launchpad.net/~wpilib/+archive/ubuntu/toolchain-beta/) for the 2019 toolchain on ubuntu 18.04.  When I try to build the example cpp project, it doesn't find any valid toolchain.  It only looks for `arm-frc-linux-gnueabi-g++`, but it needs to recognize `arm-frc2019-linux-gnueabi-g++` as a valid toolchain.  Is the toolchain not supported, or just not found? This is the output of the build with the `--info` flag.  

    ~/Downloads/GradleRIO/examples/cpp$ ./gradlew build --info
    Initialized native services in: /home/jack/.gradle/native
    The client will now receive all logging from the daemon (pid: 2722). The daemon log file: 
    /home/jack/.gradle/daemon/4.7/daemon-2722.out.log
    Starting 2nd build in daemon [uptime: 7.045 secs, performance: 98%]
    Using 1 worker leases.
    Starting Build
    Settings evaluated using settings file 
    '/home/jack/Downloads/GradleRIO/examples/cpp/settings.gradle'.
    Projects loaded. Root project using build file 
    '/home/jack/Downloads/GradleRIO/examples/cpp/build.gradle'.
    Included projects: [root project 'cpp']

    > Configure project :
    Evaluating root project 'cpp' using build file 
    '/home/jack/Downloads/GradleRIO/examples/cpp/build.gradle'.
    Destination file already exists. Skipping 'JreZulu_18u131_kickoff.ipk'
    All projects evaluated.
    Starting process 'command 'which''. Working directory: 
    /home/jack/Downloads/GradleRIO/examples/cpp Command: which arm-frc-linux-gnueabi-g++
    Successfully started process 'command 'which''
    FRC Home:
      - Valid?: false
      - Found?: false
      - Version Range:
          - Low: 5.5
          - High: 5.5
          - Is Valid?: false
      - Root: null
      - Bin: null
      - Lib: null
      - Include: null
      - Gcc: null
      - Gdb: null
    GradleRIO Home:
      - Valid?: false
     - Found?: false
       - Version Range:
          - Low: 5.5
          - High: 5.5
          - Is Valid?: false
      - Root: null
      - Bin: null
      - Lib: null
      - Include: null
      - Gcc: null
      - Gdb: null
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    A problem occurred configuring root project 'cpp'.
    > Exception thrown while executing model rule: 
    NativeComponentModelPlugin.Rules#createDefaultToolChain(NativeToolChainRegistryInternal)
       > Could not create an instance of type edu.wpi.first.gradlerio.wpi.toolchain.WPIRoboRioGcc_Decorated.
          > No valid toolchain(s) found! Information dumped to info log (run with --info)

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. 
    Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 8s

**Comment by jath03** [comment]
Could I just rename the 2019 toolchain files?

**Comment by PeterJohnson** [comment]
What are you trying to do?  The 2019 toolchain cannot be used to compile programs for a 2018 roboRio.  If you want to compile programs for 2018, use the 2018 toolchain.

**Comment by jath03** [comment]
Oh, the 2018 version wasn't installing correctly - annoying dependency stuff that I never figured out - so I just used used the 2019 version and thought that there wouldn't be much of a difference.  Nevermind then.

**Comment by JacisNonsense** [comment]
I'm gonna keep this open just so it's on the roadmao
