### ISSUE TITLE
org.gradle.internal.os.OperatingSystem is a Gradle internal API

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/GradleRIO#204]
You might want to use the guava OS inspector instead. That API is stable.

**Comment by JLLeitschuh** [comment]
Here's a replacement that's part of the public API:
https://docs.gradle.org/current/javadoc/org/gradle/nativeplatform/platform/OperatingSystem.html

**Comment by ThadHouse** [comment]
We're going to keep OperatingSystem for now. It's so commonly used its unlikely to change, and we are already highly dependent on internal APIs that we need to explicitly check every new gradle version anyway.
