### ISSUE TITLE
Cannot find Jarfile 

### ISSUE THREAD

**Issue by RedThunder7166** [wpilibsuite/GradleRIO#210]
I've tried programming our 2018 robot in Java (we previously used LabView).  I've followed the steps given to install VSCode and the Java Language extension.  I loaded the premade "Motor Controller" program, built the program fine and deployed the program fine.  

Though, when I open the Drivers Station it tells me "No Robot Code" and I get the error in the RioLog:

Error: Unable to access jarfile /home/lvuser/Motor

and it repeats infinitely.

**Comment by ThadHouse** [comment]
You cannot have spaces in your project name. Make sure that the root folder created does not have a space in it. This has been fixed in master.
