### ISSUE TITLE
Add warning if deploying without libs being downloaded

### ISSUE THREAD

**Issue by JacisNonsense** [wpilibsuite/GradleRIO#216]
It should prompt the user to first run` ./gradlew build` or trigger build from the IDE

**Comment by JLLeitschuh** [comment]
Why not just make the deploy depend upon `build`? That way this never happens and nobody ends up with stale artifacts?

**Comment by JacisNonsense** [comment]
Deploy is called when connected to robot wifi. Deploy already depends on build tasks for each artifacts. The wifi issue is what I'm trying to fix - since libs can't download when not connected to the internet

**Comment by JLLeitschuh** [comment]
Fascinating. Wouldn't this be an error case then? Not a warning? I don't understand how the deploy could succeed if the dependent libraries weren't downloaded.

**Comment by ThadHouse** [comment]
Yes, but it would be nice to have an actual message, rather then just dependency not found. Our people are REALLY bad at even the most simple of problem solving.

**Comment by JLLeitschuh** [comment]
100% agreed.

**Comment by JacisNonsense** [comment]
By warning I do mean error case - usually the build would fail, but if I can hook on build fail and check that some dependencies are, indeed, missing, I can give a more idiomatic error message.

If there are artifacts that aren't downloaded, but the deploy still succeeds, we shouldn't be the ones causing the failure

**Comment by JacisNonsense** [comment]
Wasn't meant to close that, whoops
