### ISSUE TITLE
JSON vendor library only supports 'linuxathena' classifier

### ISSUE THREAD

**Issue by JCaporuscio** [wpilibsuite/GradleRIO#219]
For dependencies in a vendor json file, only linuxathena classifier artifacts are downloaded, even when building for sim with windows/linux classifiers present in the json.

# Steps to reproduce:
[1] Create new gradlerio/vscode cpp project
[2] Install & import Phoenix.json
    Online file can be found here: http://devsite.ctr-electronics.com/maven/frcbetajson/Phoenix.json
[3] Add a "ctre/Phoenix.h" include and a Talon SRX object to Robot.cpp
[3] Build Robot Code fails 
   Expected - Phoenix is currently missing 2 sim-only libraries.  However, error message indicates missing symbols that _are_ present in "api-cpp", which should be included in the build.
[4] Expanded Archives in build/tmp indicates no desktop artifacts were download for libraries in Phoenix.json [NOT OK]

### Build Error Message
<details>
  <summary>Error Message</summary>
<pre>
> Task :linkFrcUserProgramDesktopDebugExecutable FAILED
Robot.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl ctre::phoenix::motorcontrol::can::BaseMotorController::~BaseMotorController(void)" (??1BaseMotorController@can@motorcontrol@phoenix@ctre@@UEAA@XZ) referenced in function "public: void __cdecl ctre::phoenix::motorcontrol::can::TalonSRX::`vbase destructor'(void)" (??_DTalonSRX@can@motorcontrol@phoenix@ctre@@QEAAXXZ)
Robot.obj : error LNK2019: unresolved external symbol "public: __cdecl ctre::phoenix::motorcontrol::can::TalonSRX::TalonSRX(int)" (??0TalonSRX@can@motorcontrol@phoenix@ctre@@QEAA@H@Z) referenced in
function "void __cdecl `dynamic initializer for 'myTalon''(void)" (??__EmyTalon@@YAXXZ)
Robot.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl ctre::phoenix::motorcontrol::can::TalonSRX::~TalonSRX(void)" (??1TalonSRX@can@motorcontrol@phoenix@ctre@@UEAA@XZ) referenced in function "public: void __cdecl ctre::phoenix::motorcontrol::can::TalonSRX::`vbase destructor'(void)" (??_DTalonSRX@can@motorcontrol@phoenix@ctre@@QEAAXXZ)
D:\CTR\Playground\temp\testCpp\build\exe\frcUserProgram\desktop\debug\frcUserProgram.exe : fatal error LNK1120: 3 unresolved externals
</pre>
</details>

# Other Symptoms

Another symptom presents itself if the 'linuxathena' classifier is not present for a dependency.
If a dependency only has desktop classifiers, an error is thrown indicating a null pointer exception (see below).  This suggests the dependency's classifier list is empty in gradle even though windows and linux classifiers are present in the json file.

<details>
  <summary>Error Message</summary>
<pre>
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'BasicCpp'.
> Exception thrown while executing model rule: NativeDepsPlugin.NativeDepsRules#addNativeLibs(ModelMap<Task>, NativeDepsSpec, ExtensionContainer, FlavorContainer, BuildTypeContainer, PlatformContainer)
   > java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
</pre>
</details>

**Comment by JacisNonsense** [comment]
This was indirectly fixed by the closing of #221.
FWIW, Phoenix has a bug in `WPI_TalonSRX` and `WPI_VictorSPX` that popped up upon resolving this issue: lines 24 and 25 of each .h file, `SmartDashboard` should be in lower case `smartdashboard`
