### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by vieiraPatrick** [wpilibsuite/GradleRIO#220]
Every time I try to build my code the line "import edu.wpi.first.wpilibj.IterativeRobot;" disappears and I get an error.

**Comment by PeterJohnson** [comment]
Is this with the beta?  Are you using vscode?  Is this on Windows or some other platform?  Does the line disappear when you save, or when you build/deploy?  Can you edit in a text editor outside of vscode and confirm that the line is present there, and manually build in a command prompt?

**Comment by vieiraPatrick** [comment]
Hi Peter,

It is with the Alpha version of the VS code, because I don't know how to
get access to download the Beta version. I am using windows 10. Every time
I try to save or build/deploy this happens, I also noticed that it is not
only to that one specific line, it happens when I used XboxController as
well. At first when I was using the example Getting Started it was building
normally, then after any changes I do this starts to happen. If I use the
same code with Eclipse it works.

*Patrick R. Vieira*
Southeast Career and Technical Academy
*Robotics Teacher*

"In the end, we only regret the chances we didn’t take."
*- Lewis Carroll*

**Comment by PeterJohnson** [comment]
If you go to Preferences | Settings, and search for "organize", is "Organize Imports" checked or unchecked?  Can you upload a copy of your settings.json?  (you can get to it via Preferences | Settings and then clicking the "..." icon).

**Comment by vieiraPatrick** [comment]
The option Organize Imports is not checked. I tried checking it and it
didn't change anything, so I just switched back. When I open the
settings.json it shows the following in the User Settings:

{
"java.errors.incompleteClasspath.severity": "ignore",
"wpilib.alwaysAskForTeamNumber": true
}

*Patrick R. Vieira*
Southeast Career and Technical Academy
*Robotics Teacher*

"In the end, we only regret the chances we didn’t take."
*- Lewis Carroll*

**Comment by vieiraPatrick** [comment]
Workspace settings shows the following:

{
"java.configuration.updateBuildConfiguration": "automatic",
"files.exclude": {
"**/.git": true,
"**/.svn": true,
"**/.hg": true,
"**/CVS": true,
"**/.DS_Store": true,
"bin/": true,
".classpath": true,
".project": true
},
"wpilib.online": true
}

*Patrick R. Vieira*
Southeast Career and Technical Academy
*Robotics Teacher*

"In the end, we only regret the chances we didn’t take."
*- Lewis Carroll*

**Comment by vieiraPatrick** [comment]
Does it look like I could try changing configuration or something?

*Patrick R. Vieira*
Southeast Career and Technical Academy
*Robotics Teacher*

"In the end, we only regret the chances we didn’t take."
*- Lewis Carroll*

**Comment by JacisNonsense** [comment]
I'm cleaning out old issues and I can't quite tell what's wrong with this one. @vieiraPatrick , if you're still having issues, reopen this issue, but for now I'm going to assume it's resolved
