### ISSUE TITLE
Vendor JSON does not support C++ dependencies without 'linuxathena' classifier

### ISSUE THREAD

**Issue by JCaporuscio** [wpilibsuite/GradleRIO#231]
Having cppDependencies that do not have 'linuxathena' as a valid classifier causes a NullPointerException in the native deps plug-in on build.

To reproduce this, I used a stock project that also contained the *.json file for Phoenix.
No Phoenix API calls were made in source, so the actual phoenix binary isn't necessary for build.

GradleRIO version: 2019.1.1-beta-2a
Phoenix version: 5.10.0.1

[1] Create stock Cpp project
[2] Project builds [OK]
[3] Add Phoenix to the project (without modifying cpp source files)
[4] remove "linuxathena" as a valid classifier for any of the cppDependencies
[5] Build project fails [NOT OK]

Being able to have dependencies that are desktop-only are critical for vendors to support simulation.  CTRE has simulation dependencies that are desktop-only - this will be a blocking issue to support simulation.

<details><summary>Error Code</summary>
<p>
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'BasicCpp'.
> Exception thrown while executing model rule: NativeDepsPlugin.NativeDepsRules#addNativeLibs(ModelMap<Task>, NativeDepsSpec, ExtensionContainer, FlavorContainer, BuildTypeContainer, PlatformContainer)
   > java.lang.NullPointerException (no error message)
</p>
</details>

**Comment by JacisNonsense** [comment]
This will be resolved in #229
