### ISSUE TITLE
Execution failed for task ':discoverRoborio'

### ISSUE THREAD

**Issue by nathanmutin** [wpilibsuite/GradleRIO#233]
All my team can't deploy any robot code to the RoboRio with Gradle.
We can deploy from Eclipse without issues.
Here are the logs : 
- ./gradlex delpoy : [https://gist.github.com/nathanmutin/3e53a95dd9cd40602e91cc522e75f837](url)
- ./gradlex delpoy --info : [https://gist.github.com/nathanmutin/cf1d19dd8d0d785f6a07d368e25a0d6a](url)
- ./gradlex delpoy --stacktrace : [https://gist.github.com/nathanmutin/7ecc0aa59e74f48ff7a4de46fc0cc780](url)

**Comment by nathanmutin** [comment]
Here is the output for the deploy in Eclipse :
Buildfile: C:\Users\Nathan\Documents\Robo'Lyon\Command-Based_Scorpion\build.xml
Trying to override old definition of task classloader
get-target-ip:
     [echo] Finding roboRIO...
[find-roborio] could not resolve roboRIO-5553-FRC.frc-field.local
[find-roborio] resolved roboRIO-5553-FRC.lan to 10.55.53.247
[find-roborio] could not resolve roboRIO-5553-FRC.local
[find-roborio] trying 10.55.53.247
[find-roborio] trying 172.22.11.2
[find-roborio] trying 10.55.53.2
[find-roborio] could not get IP from DS
     [echo] roboRIO found at 10.55.53.247, image FRC_roboRIO_2018_v17
dependencies:
     [echo] roboRIO image version validated
deploy:
   [webdav] getting http://10.55.53.247/files/usr/local/frc/lib/WPI_Native_Libraries.properties
   [webdav] getting http://10.55.53.247/files/usr/local/frc/lib/User_Libraries.properties
  [sshexec] Connecting to 10.55.53.247:22
  [sshexec] cmd : rm -f /home/lvuser/FRCUserProgram
     [echo] [athena-deploy] Copying code over.
   [webdav] deleting http://10.55.53.247/files/home/lvuser/FRCUserProgram
   [webdav] putting C:\Users\Nathan\Documents\Robo'Lyon\Command-Based_Scorpion\Debug\FRCUserProgram to http://10.55.53.247/files/home/lvuser/FRCUserProgram
   [webdav] deleting http://10.55.53.247/files/home/lvuser/robotCommand
   [webdav] putting C:\Users\Nathan\wpilib\cpp\current\ant\robotCommand to http://10.55.53.247/files/home/lvuser/robotCommand
     [echo] [athena-deploy] Starting program.
  [sshexec] Connecting to 10.55.53.247:22
  [sshexec] cmd : . /etc/profile.d/natinst-path.sh; chown lvuser /home/lvuser/FRCUserProgram; setcap 'cap_sys_nice=pe' /home/lvuser/FRCUserProgram; chmod a+x /home/lvuser/FRCUserProgram; /usr/local/frc/bin/frcKillRobot.sh -t -r; sync
BUILD SUCCESSFUL
Total time: 6 seconds

**Comment by JacisNonsense** [comment]
So it's finding it at `roborio-XXXX-frc.lan`, which was added to the GradleRIO search list in Beta. It seems you're on alpha, so this issue has been fixed but isn't accessible unless you're a beta team.

You can manually add it to the list with:
```
locations {
    ssh {
        address = "roborio-5553-frc.lan"
        user = "admin"
        password = ""
        ipv6 = false
    }
}
```
which will go inside of your RoboRIO target block in your build.gradle

**Comment by nathanmutin** [comment]
It's working !!!!!!!
Thank you very much.
