### ISSUE TITLE
[Question] Where can I find the 2019 RoboRIO Image?

### ISSUE THREAD

**Issue by Tommsy64** [wpilibsuite/GradleRIO#265]
I have tried following the guide [here](https://wpilib.screenstepslive.com/s/currentCS/m/79833/l/1004055-installing-the-frc-update-suite-all-languages). Although it shows images for FRC Update Suite 2019, the download link points to the 2018 version. Do I need to be part of the closed beta to use the 2019 firmware?

**Comment by ThadHouse** [comment]
Yes, you need to be a part of the closed beta to currently use the 2019 firmware. You can use the alpha, which uses the 2018 inage, and you can find the instructions for that on screen steps.
