### ISSUE TITLE
Simulate runs with project directory as working directory - `src/main/deploy` isn't handled for simulation

### ISSUE THREAD

**Issue by JaciBrunning** [wpilibsuite/GradleRIO#311]

**Comment by blu28** [comment]
I just hit this one. Any ideas for a workaround?

**Comment by JacisNonsense** [comment]
You can check if you're in a simulation through `RobotBase.isSimulation`, and add `src/main/deploy` to the path if so

**Comment by blu28** [comment]
> You can check if you're in a simulation through `RobotBase.isSimulation`, and add `src/main/deploy` to the path if so

Yes, thank you, I hit on this solution too. Github doesn't seem to have a way to "vote" or say "I hit this one too", but i wanted to make sure you knew it was being seen "in the wild." 

Thank you for all the work you are doing on this. Desktop simulation is a game changer for our team.

**Comment by Starlight220** [comment]
[`Filesystem.getDeployDirectory()`](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/Filesystem.java#L59) correctly returns `src/main/deploy` in sim, and files can be retrieved correctly (I just verified this). Therefore I think that this issue has been resolved and can be closed.

**Comment by AustinShalit** [comment]
Closed by https://github.com/wpilibsuite/allwpilib/pull/2293/
