### ISSUE TITLE
Java Vendor Library not Deploying Properly - ClassNotFoundException

### ISSUE THREAD

**Issue by sleepisfortheweak** [wpilibsuite/GradleRIO#315]
Hopefully I'm just missing something here. I'm publishing my vendor library using the new VS Code JSON method. Currently in JAVA. I've got VS Code picking up the Vendor Library and compiling successfully. However, when the code runs I get a ClassNotFoundException when it attempts to load my class. See attached error, JSON, and JAR files. Thanks for your help.

`
********** Robot program starting **********
Unhandled exception instantiating robot jdk.internal.loader.BuiltinClassLoader java.lang.ClassNotFoundException: edu.wpi.first.wpilibj.util.UncleanStatusException
Error at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source): Unhandled exception instantiating robot jdk.internal.loader.BuiltinClassLoader java.lang.ClassNotFoundException: edu.wpi.first.wpilibj.util.UncleanStatusException
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at frc.robot.Robot.<clinit>(Robot.java:27)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:221)
at frc.robot.Main.main(Main.java:27)
`

[LightDrive-java-2019.02.13.zip](https://github.com/wpilibsuite/GradleRIO/files/2863795/LightDrive-java-2019.02.13.zip)

[LightDrive.json.txt](https://github.com/wpilibsuite/GradleRIO/files/2863796/LightDrive.json.txt)

**Comment by PeterJohnson** [comment]
There is no such class `edu.wpi.first.wpilibj.util.UncleanStatusException`.  Did you mean `edu.wpi.first.hal.util.UncleanStatusException`?  I'm not sure how you successfully compiled.

**Comment by sleepisfortheweak** [comment]
That error is copied directly from GradleRIO output. Is that a clue to what happened? I just imaged the RIO with the 2019 FRC update and updated VS Code's GradleRIO extension from alpha release to latest. Once I installed my Vendor Library, VS Code picked up the LightDrive classes and built successfully.

**Comment by ThadHouse** [comment]
You would need the libraries recompiled for 2019. 2018 libraries will not work with the 2019 setup. Because some of the classes, especially the low level communication classes, have changed.

**Comment by sleepisfortheweak** [comment]
Good call. That's probably it. I thought maybe it was a Java version issue, but didn't think about WPILib portion. I will attempt to recompile that JAR against 2019 WPILib.

**Comment by sleepisfortheweak** [comment]
Yes, that was the error. I built with the 2019 WPILib and I can now deploy successfully. Thanks for the help.
