### ISSUE TITLE
Gradle 5.2 Breaks GradleRIO DeployPlugin

### ISSUE THREAD

**Issue by iboyperson** [wpilibsuite/GradleRIO#319]
Updating the wrapper to 5.2 causes builds to fail with DeployPlugin throwing a NullPointerException.

Build Scan is available here: https://scans.gradle.com/s/r52znjioy7aes/

**Comment by ThadHouse** [comment]
We've seen this, but we will only support 5.0 for the season. We likely will not update during the season in order to not risk breaking anything.

**Comment by ThadHouse** [comment]
I looked into doing an update, and it would break 5.0 compatibility. So 5.0 will be the only compatible version for the 2019 season.

**Comment by ThadHouse** [comment]
For 2020, this has been fixed. Right now, master requires 5.4.1, but we will likely be at 6.0 for the season.
