### ISSUE TITLE
Allow Deployment of Custom Binaries

### ISSUE THREAD

**Issue by carlosgj** [wpilibsuite/GradleRIO#333]
GradleRIO should be able to build Java/C++ code with the normal toolchains, but then deploy the resulting artifacts to arbitrary paths on the roboRIO, without the steps for normal robot code deployment (frckillrobot, setting up robotcommand, etc.) This would be useful for deploying diagnostic processes or other software which is not part of the normal robot code.

**Comment by JacisNonsense** [comment]
GradleRIO (or, more accurately, EmbeddedTools), allows you to deploy custom binaries as you will (see the implementation details of `FRCNativeArtifact` and `FRCJavaArtifact` in this repo to see how we extend them).

If you still want to deploy a 'robot binary', but without the other logic (frckillrobot, robotcommand, etc), you can call a few configuration options inside of the artifact closure:
```gradle
artifacts {
    artifact('frcJava', edu.wpi.first.gradlerio.frc.FRCJavaArtifact) {
        /* all the other stuff like normal */

        robotCommand = false    // Disable robotCommand
        predeploy.clear()              // Prevents frcKillRobot.sh and other predeploy tasks
        postdeploy.clear()            // Prevents frcKillRobot.sh (restart) and other postdeploy tasks (chmod, sync, ldconfig)
    }
}
```

Likewise for FRCNativeArtifact.
