### ISSUE TITLE
How To Use The Latest Command Framework In Our Project?

### ISSUE THREAD

**Issue by ScarletMetal** [wpilibsuite/GradleRIO#352]
Hi,

My team is very interested in testing the new bleeding edge Command Based framework described [here](https://frc-docs.readthedocs.io/en/latest/docs/software/commandbased/index.html). We know that the framework is still very new, yet we still wanted to check with you. Is there a way for us to import it into our project using GradleRIO? or should we just compile it on our own into a local jar? 

Thanks for your answer!

**Comment by PeterJohnson** [comment]
@Oblarg has created a jitpack that you can use for testing it with 2019: add this to the gradle dependencies: `compile 'com.github.Oblarg:command-rewrite-jitpack:1.5.1'`

You might also consider applying to be a beta tester; applications should be opening soon.
