### ISSUE TITLE
Having problems with building

### ISSUE THREAD

**Issue by katzuv** [wpilibsuite/GradleRIO#373]
Hi,
[This](https://github.com/katzuv/Robot-2018-Revised) is our repository, it includes all the Gradle files including [`build.gradle`](https://github.com/katzuv/Robot-2018-Revised/blob/github-ci/build.gradle).
When running `./gradlew build --info` we get [this](https://github.com/katzuv/Robot-2018-Revised/commit/c1a80e93185e8cb5a430297ebdc8935f10c4489e/checks?check_suite_id=301973208) log.
We do not really understand what is the issue and how we fix it, so we'd like to get any help.
Thanks in advance!

**Comment by PeterJohnson** [comment]
You’re trying to use 2019 vendor dependencies (in particular for NavX) with 2020 wpilib.  That won’t work.

**Comment by katzuv** [comment]
Thank you, I changed the version of GradleRIO to `2019.4.1`.
However, now I'm getting the following issue:
```
* Where:
Build file '/home/runner/work/Robot-2018-Revised/Robot-2018-Revised/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating root project 'Robot-2018-Revised'.
> No signature of method: edu.wpi.first.gradlerio.wpi.dependencies.WPIDepsExtension.wpilibJni() is applicable for argument types: (String) values: [linuxathena]
  Possible solutions: wpilibJni(), wpilib(), wpilibJars()
```
Is there anything else I need to change to all the version will match?
Thanks!
(Also, I pointed earlier to another version of the `build.gradle` file. [This](https://github.com/katzuv/Robot-2018-Revised/blob/github-ci/build.gradle) is the correct version, sorry about it.)

**Comment by ThadHouse** [comment]
When moving back to 2019.4.1, you need the following dependencies block.

```
dependencies {
    compile wpi.deps.wpilib()
    compile wpi.deps.vendor.java()
    nativeZip wpi.deps.vendor.jni(wpi.platforms.roborio)
    nativeDesktopZip wpi.deps.vendor.jni(wpi.platforms.desktop)
    testCompile 'junit:junit:4.12'
}
```

You can completely replace the existing one. That was on the list of things changed for 2020.

**Comment by katzuv** [comment]
Hey, I'm still getting issues, although I believe I fixed all the version-compatibility issues. Links:
- [`build.gradle`](https://github.com/katzuv/Robot-2018-Revised/blob/github-ci/build.gradle)
- [`gradle.yml`](https://github.com/katzuv/Robot-2018-Revised/blob/github-ci/.github/workflows/gradle.yml)
- [Log](https://github.com/katzuv/Robot-2018-Revised/commit/bbe4222822cae7ea47fb7a3ebca77b535e2e4fca/checks?check_suite_id=303600871)

Thanks a lot for your help!

**Comment by prateekma** [comment]
The first.wpi.edu domain seems to be down today

**Comment by katzuv** [comment]
Oh, you're probably right. The domain was up for a few minutes, then the build was successful, now the site is down again and the build fails again.

**Comment by katzuv** [comment]
Thanks, everyone! Finally, I managed to get the pipeline up and running. Thank you all for your help!
