### ISSUE TITLE
Set duplicatesStrategy of jar in templates

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/GradleRIO#378]
Otherwise, a new deprecation warning occurs.

**Comment by Starlight220** [comment]
Is this still relevant? It's a bit late to change the template for 2021...

**Comment by ThadHouse** [comment]
It's still relevant, and not too late to change. It's a simple change that won't break anything.

**Comment by Starlight220** [comment]
So what do we want to set `jar.duplicatesStrategy` to?

**Comment by sciencewhiz** [comment]
Fixed by #516

**Comment by ThadHouse** [comment]
Fixed, so closing.
