### ISSUE TITLE
Template Project deployJreRoborio Fails

### ISSUE THREAD

**Issue by Chris2fourlaw** [wpilibsuite/GradleRIO#391]
Deploy to robot fails. Tested on new timed robot template project with no code changes.

https://pastebin.com/raw/pUsaUU8T

**Comment by ThadHouse** [comment]
If you didn't use the offline installer, you need to run a build once before running a deploy, in order to cache that file.

**Comment by PeterJohnson** [comment]
You need to use the installer first so the artifacts are local to your computer.

**Comment by Chris2fourlaw** [comment]
Building works fine, saw downloads and everything on the first time. Guess this file isn't being downloaded?

**Comment by ThadHouse** [comment]
The default deploy in VS Code always deploys in offline mode. I'll look into that, but you can open an integrated terminal with Ctrl + ~, and then just run

`./gradlew deploy  -PteamNumber=9973  -Dorg.gradle.java.home="/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home"`

That will cause a deploy to run without offline mode. You will only need to do this once, and you will need internet.

**Comment by Chris2fourlaw** [comment]
That solved it. Thanks. I think it would be beneficial to throw that download in with build if possible.

**Comment by Starlight220** [comment]
I believe the missing step here is `installRoborioToolchain`, but I'm not that sure. If it is, adding the `installRoborioToolchain` as a dependency of `deployJreRoborio` would fix this. @ThadHouse, am I missing something here? I can fix this if this is indeed the problem.

**Comment by PeterJohnson** [comment]
No, installRoborioToolchain is used to install the C++ compiler on the local system for use with C++ projects.

**Comment by Starlight220** [comment]
Then how do we want to resolve this? What's missing is `edu.wpi.first.jdk:roborio-2020:11.0.4u10-2`, I believe that is the RoboRio C++ compiler that is installed using `installRoborioToolchain`.

**Comment by ThadHouse** [comment]
Its supposed to grab the jdk during build, but we've seen cases where Gradle just decides to bypass that for no reason. There's not much we can do, I can't consistently repro it.

**Comment by Starlight220** [comment]
Ok. So any ideas as to how to fix this? I assume that the jre fetching task is a dependency of `deployJreRoborio`? What task is that?

**Comment by PeterJohnson** [comment]
Going back to the original pastebin, this was a C++ project?  Why was it trying to deploy the JRE at all?

**Comment by ThadHouse** [comment]
Oh I didn't even notice that. Thats the bug. `build` in C++ won't download that. I'll dig in, because thats something I hadn't seen.

**Comment by Starlight220** [comment]
I think I found the issue: 
https://github.com/wpilibsuite/GradleRIO/blob/6646f69cd953c03a1be98c96662a18e1075151a6/src/main/groovy/edu/wpi/first/gradlerio/frc/FRCJREArtifact.groovy#L15
That function/whatever should return `false` if it's a C++ project.

**Comment by ThadHouse** [comment]
It's set to false in other places.

**Comment by ThadHouse** [comment]
This was fixed in the rewrite, as the JDK deploy is 100% contained in java projects now.
