### ISSUE TITLE
Getting errors when I simulate with wpi.deps.sim.nt_ds

### ISSUE THREAD

**Issue by amorygalili** [wpilibsuite/GradleRIO#398]
In the _build.gradle_ file I changed `simulation wpi.deps.sim.gui(wpi.platforms.desktop, false)
` to `simulation wpi.deps.sim.nt_ds(wpi.platforms.desktop, false)` and I'm getting these errors:

> Execution failed for task ':simulateJava'.
> > Could not resolve all files for configuration ':simulation'.
>    > Could not find edu.wpi.first.halsim.ds:halsim-ds-nt:2020.2.2.
>      Searched in the following locations:
>        - file:/Users/amorygalili/wpilib/2020/maven/edu/wpi/first/halsim/ds/halsim-ds-nt/2020.2.2/halsim-ds-nt-2020.2.2.pom
>        - https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/halsim/ds/halsim-ds-nt/2020.2.2/halsim-ds-nt-2020.2.2.pom
>        - https://repo.maven.apache.org/maven2/edu/wpi/first/halsim/ds/halsim-ds-nt/2020.2.2/halsim-ds-nt-2020.2.2.pom
>      Required by:
>          project :

[https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/halsim/ds/halsim-ds-nt/2020.2.2/halsim-ds-nt-2020.2.2.pom](url) seems to be broken. The correct link seems to be [https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/halsim/halsim_ds_nt/2020.2.2/halsim_ds_nt-2020.2.2.pom](url).

The offending code seems to be this: https://github.com/wpilibsuite/GradleRIO/blob/master/src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPISimDepsExtension.groovy?fbclid=IwAR3AwI0_6icoSiO0O4d73IMHJ52akj-WPnDgEXe1PSZB78Jj-GWNTZ0R6Lk#L24

This line of code seems to work in the _build.gradle_ file: `simulation(["edu.wpi.first.halsim:halsim_ds_nt:2020.2.2:${wpi.platforms.desktop}${false ? 'debug' : ''}@zip".toString()])`

So I'm guessing the broken code in _WPISimDepsExtension.groovy_ should be changed to return `["edu.wpi.first.halsim:halsim_ds_nt:${wpi.wpilibVersion}:${platform}${debug ? 'debug' : ''}@zip".toString()]`? There seems to be a similar problem with some of the other sim deps.

**Comment by ThadHouse** [comment]
Oh, whoops. I'll make sure this gets fixed for the next release. You are right that's all you need to do to work around the issue.
