### ISSUE TITLE
Have simulateJava search for the WPILib installed JDK

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/GradleRIO#400]
Currently, it will use the executing JDK exclusively, which is unlikely to be the WPILib JDK because of the use case. This is causing issues like #399 because the C++ runtime is only installed to the WPILib JDK. We should search for the wpilib one and run with that if possible, otherwise print out a message saying the latest C++ runtime might be required.

**Comment by Starlight220** [comment]
This stayed open after a PR/Issue linking fault; this can be closed.
