### ISSUE TITLE
C++ SimGUI should not need VSCode

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/GradleRIO#427]
Not sure what the root issue is. This should be fixed as it becomes especially important with WS. Java works as expected.

**Comment by ThadHouse** [comment]
Its not that it needs VS Code, its just that the tasks to run from gradle directly are much harder to set up and time consuming to get right.

**Comment by ThadHouse** [comment]
Realistically, I want to rewrite how sim libraries are loaded so we don't have to worry about the debug release split from the user side. But thats a rewrite of functionality in gradlerio I definitely will not have time to get to this season.

**Comment by Daltz333** [comment]
Is this done?

**Comment by sciencewhiz** [comment]
This was done. It's simulateNative
