### ISSUE TITLE
Move version number to properties file

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/GradleRIO#428]
In order to make the automation scripts a little bit cleaner, we should move the version number here:
https://github.com/wpilibsuite/GradleRIO/blob/7473e314ac61f8ee5a89b027c2f2a7b75da69ee7/build.gradle#L42

to a properties file.

**Comment by Starlight220** [comment]
Would moving it to a root `gradle.properties` (doesn't exist yet) be sufficient/appropriate? 

And if already, we should check to see if there are any other properties that can be moved there - maybe WPILib/tools versions?

**Comment by AustinShalit** [comment]
Yes and sure.
