### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/GradleRIO#435]
Most WPILib repos have already migrated, this one hasn't. A `.travis.yml` file exists even though we haven't used TravisCI for quite a while. I can work on a migration PR soon if wanted.

**Comment by AustinShalit** [comment]
Note that right now only Azure is enabled. The travis.yml is unused.

**Comment by Starlight220** [comment]
I know that Travis is disabled (and I said so in the OP).  The unused `.travis.yml` file still exists - why?
So should I work on a PR to migrate to Actions? And should it include deletion of the old CI files?

**Comment by AustinShalit** [comment]
Sure and yes.
