### ISSUE TITLE
Update for latest roboRIO Images

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/GradleRIO#457]
For the next beta we need to add support for `v2` and `v3.*`. The `v3.*` is a new version format that means we can capture updates to the roboRIO image that do not affect the FPGA or compiler versions.

**Comment by Starlight220** [comment]
Is it anything more complicated than changing/adding version strings?

**Comment by Starlight220** [comment]
This can be closed, the PR was squashed and added directly in dc9a02a.
