### ISSUE TITLE
Offline mode for vendordep task has bad control key

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/GradleRIO#463]
The task runs on local/offline mode (fetches from user wpilib folder) if the URL starts with `$FRCLOCAL`. The problem is that bash and powershell recognize `$FRCLOCAL` as an undefined variable, causing the task to run online with an invalid URL. 

The fix is easy: change the start key to something that won't be recognized as a variable, the question is what.
An option:
- `FRCLOCAL` (no non-letter prefix, though a valid URL still won't start with it)
- anything else? IDK.

Documentation on frc-docs [here](https://docs.wpilib.org/en/latest/docs/software/vscode-overview/3rd-party-libraries.html#command-line-interface-online) needs to be updated with the new symbol. 

Clarification: the **online mode works as expected**. The problem only exists with the offline/local mode.

**Comment by ItayZiv** [comment]
I think FRCLOCAL would be fitting, I doubt any kind of real URL could be confused with that.
