### ISSUE TITLE
Set custom environment variables for simulation

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/GradleRIO#465]
TestPlugin, JavaSimulationTask, and NativeSimulationTask set the environment variables for the simulation process but have no way to add custom variables.  This is needed to make use of the websocket extension more user-friendly.

**Comment by Starlight220** [comment]
Would this be set by DSL or elsewhere?
If DSL, would this syntax be acceptable?
```groovy
simulateJava {
  envVar "myvariable", "value"
}
```
I can also add overloads that would take an `int` for the value if relevant.
