### ISSUE TITLE
No console output on simulate*Executable tasks

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/GradleRIO#467]
Reported by @calcmogul.

After looking into this, it would seem that:
- on Windows, output is rendered in the console as expected.
- on UNIX, output is redirected into a `stdout/<executable>.log` file ([source](https://github.com/wpilibsuite/GradleRIO/blob/18daacc414044b07792ec360a8eae554a622864e/src/main/groovy/edu/wpi/first/gradlerio/ExternalLaunchTask.groovy#L78))

> this works, but I have to Ctrl-C gradle to stop it after I close the sim GUI. expected, but not ideal:
```groovy
task simConsole(type: Exec) {
    workingDir 'build/stdout'
    commandLine 'tail', '-f', 'simulateFrcUserProgramLinuxx86-64DebugExecutable.log'
    dependsOn 'simulateFrcUserProgramLinuxx86-64DebugExecutable'
}

task simulate {
    dependsOn 'removeLogs'
    dependsOn 'simConsole'
}
```

**Comment by Starlight220** [comment]
@ThadHouse is there a reason that `ProcessBuilder` is used and not `Exec` (or similar), and UNIX console output is redirected to a file?

**Comment by ThadHouse** [comment]
This should be fixed in 2022. We can reopen if its not.
