### ISSUE TITLE
Gradle does not build with new java versions

### ISSUE THREAD

**Issue by indexlongrun** [wpilibsuite/GradleRIO#498]
The gradle build fails with exception when using new java versions (JDK 14,15): 
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7  and java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

What fixed it for me was: 
https://stackoverflow.com/questions/61289461/java-lang-noclassdeffounderror-could-not-initialize-class-org-codehaus-groovy-v

I changed gradle version in
main/examples/java/gradle/wrapper/gradle-wrapper.properties

from:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-bin.zip

to:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.2-bin.zip

And then the build succeeded

**Comment by ThadHouse** [comment]
We do not support running on JDKs newer then 11 and Gradle versions other than 6.0 currently. Java sometimes works, but the native setup does break. 2022 we will be updating to the latest version of Gradle, however we still recommend running on Java 11 even then, as that is what we will support on the roborio.

**Comment by Starlight220** [comment]
@Daltz333 I suggest reopening this in frc-docs to add to the Known Issues section.

**Comment by ThadHouse** [comment]
This isn't really a great thing for known issues, as teams should be using the installer. Something small saying only Java 11 and Gradle 6 is probably fine, but that'd be it. Workarounds of updating Gradle versions are definitely a no.

**Comment by Starlight220** [comment]
I meant without the workaround, something like this:

- **Error:** ```java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 and java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache```
- **Solution?:** You are somehow using a newer JDK or Gradle version. The only supported versions are Java 11 and Gradle 6.0. If you are using those versions and are getting this error, please [open an issue] (gradlerio/issues/new).

**Comment by Daltz333** [comment]
That issue isn't just a JDK version mismatch. It can be a corrupted cache too.

**Comment by Starlight220** [comment]
Either way, do we want to doc it as a known issue or something?

**Comment by Daltz333** [comment]
I wouldn't. It's so incredibly rare, and it's very generic, not specific to FRC. We should only document it if

1. More than a miniscule minority face it.
2. It's specific to FRC
