### ISSUE TITLE
C++ simulation task has incorrect working directory

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/GradleRIO#499]
Running `./gradlew simulateCpp` (with the following block in the `build.gradle`) has the current working directory in `/path/to/project/build/install/frcUserProgram/osxx86-64/debug/lib`. This means that `frc::filesystem::GetDeployDirectory()` will not work properly in simulation.

```
task simulateCpp {
    dependsOn 'simulateFrcUserProgram' + wpi.platforms.desktop.capitalize() + 'DebugExecutable'
}
```

**Comment by ThadHouse** [comment]
This is on the list of things to make sure I get right in the 2022 update.

**Comment by calcmogul** [comment]
The test task has the same working directory issue.

**Comment by ThadHouse** [comment]
This should be fixed for 2022.
