### ISSUE TITLE
Use repository filtering to ensure vendors libraries are only loaded from their own repos

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/GradleRIO#500]
https://docs.gradle.org/6.3/userguide/declaring_repositories.html#sec:repository-content-filtering

**Comment by sciencewhiz** [comment]
Was this included in #516?

**Comment by ThadHouse** [comment]
No

**Comment by msoucy** [comment]
Any word on whether this will get included? I'm currently running into an issue related to a misbehaving web server returning the wrong error code, which Gradle is picking up as a proper .XML file

**Comment by ThadHouse** [comment]
I'll make sure it gets included. Just to double check, are you seeing the error with a 2021 project? Or with the 2022 beta?

**Comment by msoucy** [comment]
With a 2021 project, on a new computer.
