### ISSUE TITLE
Import Vendor Dependency From Library

### ISSUE THREAD

**Issue by msoucy** [wpilibsuite/GradleRIO#541]
Currently, if code is built as a library but pulls in vendor dependencies via vendordeps and json, the exact same json files need to be included in the separate robot code repository. If not, then Gradle will complain about not being able to find some of the dependencies, because using `api()` adds references to the packages, but not the repositories that they come from.

Ideally those could be propagated with the library information, but that seems like it'd be more of a Gradle change itself.

**Comment by ThadHouse** [comment]
That's not something we can solve from our side. The maven metadata format has no way to also specify a repository. This would require some changes far below our level.

**Comment by ThadHouse** [comment]
Since this isn't something we can do, I'm going to close this.
