### ISSUE TITLE
Allow deploying only the deploy folder without also building robot code

### ISSUE THREAD

**Issue by brennenputh** [wpilibsuite/GradleRIO#605]
A gradle task should be added that would allow to simply copy the deploy folder to the rio, without building and sending robot code over.  This would allow teams to more quickly test systems that are entirely data-driven, such as autonomous paths made with PathWeaver/PathPlanner.

**Comment by ThadHouse** [comment]
Looking, I realized there is actually a solution to this that exists today. Inside any artifact (Like `frcStaticFileDeploy`) in your build.gradle file, you can add 

`setDeployStage(it, 'BeforeProgramKill')`

and that will cause the deploy task to be the first thing ran on a deploy, before robot code is killed. You can just manually run `deployfrcStaticFilesDeploy` if you have a stock template to deploy just that artifact.
