### ISSUE TITLE
Turning robot off while deploying java code erases Java lib from RoboRIO

### ISSUE THREAD

**Issue by WTFogland** [wpilibsuite/GradleRIO#609]
**Describe the bug**
When deploying code to the robot, the power was cut. After rebooting the robot and attempting to deploy again, the code would always show as "Build successful" and deploy, but nothing would come up on the RoboRIO log and the driver station would indicate "No code". When checking the RoboRIO's status on the driver station, it was noticed that the java library was gone. After reimaging the robot, code was able to be successfully put back on the RoboRIO.

**Desktop (please complete the following information):**
 - WPILib Version: 2022.4.1
 - OS: Windows 11

![image](https://user-images.githubusercontent.com/35082015/160162463-3ff2c3e9-50b9-4ff9-aac7-fec59764f3d3.png)

**Comment by PeterJohnson** [comment]
Fixed in #618.
