### ISSUE TITLE
Incompatibility with Eclipse Plugins

### ISSUE THREAD

**Issue by JacisNonsense** [wpilibsuite/GradleRIO#62]
Due to the single admin SSH session, the frcUserProgram file conflicts with that being deployed by the eclipse plugins, causing a potential deadlock in the deploy process since frcKillRobot.sh doesn't affect other users' owned processes

**Comment by calcmogul** [comment]
This deadlock behavior occurs even on a freshly reimaged roboRIO with the Eclipse deploy never being run.

**Comment by JacisNonsense** [comment]
I can't seem to recreate this issue. I'll try a reimage

**Comment by calcmogul** [comment]
I can't reproduce this anymore with the v16 image and GradleRIO 2018.01.22.

**Comment by JacisNonsense** [comment]
Huh, alright then. I'll keep this open but label it as such. I've tried multiple times but I can't seem to reproduce it either.

Anyone: bump this thread if you see an issue like this
