### ISSUE TITLE
Running GradleRIO open Command launches additional Command Prompt

### ISSUE THREAD

**Issue by JDaniel29** [wpilibsuite/GradleRIO#64]
Whenever I run `gradlew shuffleboard` or `gradlew smartdashboard`, all that occurs is that my project is built and an additional command prompt is opened to the project directory. The weird thing is that no errors are thrown, and I can open the jar files of the tools by double-clicking on them or running the `java -jar` commands. However, the programs don't open when I run the gradle commands.

**Comment by JacisNonsense** [comment]
They are intended to spawn a new command window, but that command window is also intended to run the shuffleboard jar. Can you send a screenshot of what you're seeing?

**Comment by JDaniel29** [comment]
Here you go:

The CMD that pops up:
![image](https://user-images.githubusercontent.com/19209598/34687605-45d5f2b4-f47d-11e7-8705-76f271917d01.png)

The output in the terminal:
![image](https://user-images.githubusercontent.com/19209598/34687652-6db362d0-f47d-11e7-9178-5ef97be5dfdf.png)

**Comment by JacisNonsense** [comment]
I noticed this same issue when the `java` command was not on the system PATH. Can you add your JDK/JRE bin directory to your system path?

**Comment by JDaniel29** [comment]
I added the bin for my JDK and JRE to the path and it still is only throwing up the blank command prompt. However, this time the command prompt has a link to the bat file in the header.

![image](https://user-images.githubusercontent.com/19209598/35190362-4f80c0e6-fe2d-11e7-9418-720dcf6d0cd2.png)

**Comment by JacisNonsense** [comment]
Try running `./gradlew shuffleboard -Pheadless` and run the file it tells you to run

**Comment by JDaniel29** [comment]
OK, when I ran this command and the file, the shuffleboard launched.

**Comment by firecrafty** [comment]
Is there any fix planned for this? This is really inconvenient and its easier to just download and keep the jar on my desktop.

**Comment by JacisNonsense** [comment]
See #127
