### ISSUE TITLE
Check if vendor library is compatible with wpilib version

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/GradleRIO#640]
It's very common for people to try to use vendor libraries that haven't been built with the current year's WPILib version, and all they get are compile errors that aren't obvious where the problem lies. A field should be added to the vendordep JSON that shows the WPILib year it's built against, and gradlerio should validate that as part of the build process.

**Comment by JCaporuscio** [comment]
Just logging my support for this - my understanding is the intent is to use the "frcYear" parameter already in the vendordep.
Having this for 2024 would be helpful.
