### ISSUE TITLE
RIO Firmware check should be added. 

### ISSUE THREAD

**Issue by iboyperson** [wpilibsuite/GradleRIO#67]
When building a project with GradleRIO the deploy claimed success but when run with the official ant build scripts the deploy errored because our RIO has not had the firmware updated. A similar feature would be a good Idea to have in GradleRIO as the build was actually not successful.

**Comment by JacisNonsense** [comment]
I've added this to the 2019 Roadmap, although I may implement it before the end of the season

**Comment by iboyperson** [comment]
Great Thanks!

**Comment by david476** [comment]
My team is working on setting up OpenRIO and we weren't able to deploy until we flashed the RoboRIO for this season. Would it at least make sense to add a warning in the docs/ readme?

**Comment by JacisNonsense** [comment]
A lack of updated firmware doesn't cause a deploy to fail. It will still send over the code, but the code won't run since it will crash immediately. If your RoboRIO just straight up doesn't have an image on it, of course the deploy is going to fail.

**Comment by JacisNonsense** [comment]
This is implemented now, forgot to close earlier
