### ISSUE TITLE
Error out early if building on OneDrive

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/GradleRIO#677]
OneDrive breaks caching (and almost certainly other things too, like native extraction), so we should check early if the project is on OneDrive and error out if it is.

**Comment by spacey-sooty** [comment]
Hey @PeterJohnson  I can try and implement this, I am currently thinking to take the full directory of the project and check if OneDrive is a string within it. Does this seem good or is there a different implementation that you had in mind?

**Comment by PeterJohnson** [comment]
That's pretty much exactly what I was thinking.  It's unlikely that will hit false positives (e.g. someone names their user or project "OneDrive" feels unlikely).

**Comment by spacey-sooty** [comment]
Hey @PeterJohnson  I thought something like that was unlikely as well but we might want to add a note somewhere in the documentation about not creating projects in OneDrive. Not 100% sure where we would put that but I'm more than happy to add a note to the docs if you tell me where to

**Comment by PeterJohnson** [comment]
That’s why there’s also a companion issue to this one on vscode-wpilib. If we do the same detection there it can warn when opening or prevent creation of a project, which should cover most users.

**Comment by spacey-sooty** [comment]
@PeterJohnson that sounds good I hadnt seen that, I would guess most people not creating their project using the vscode creator would be keeping track of issues here
