### ISSUE TITLE
./gradlew generateCompileCommands outputs no compile_command.json

### ISSUE THREAD

**Issue by spacey-sooty** [wpilibsuite/GradleRIO#697]

**Comment by ThadHouse** [comment]
It generates into the build folder, but the location will be changing again in the next beta release and for the 2024 season.

**Comment by spacey-sooty** [comment]
> It generates into the build folder, but the location will be changing again in the next beta release and for the 2024 season.
> 
> It will generate into `build/TargetedCompileCommands/targetplatformandbuildtype`.

This isn't documented, could it be worth to mention it in FRC docs?

**Comment by ThadHouse** [comment]
The only part is we don't want to recommend compile_commands for general users. There are a lot of pitfalls that many teams wouldn't know about, that the built in intellisense doesn't have.

**Comment by spacey-sooty** [comment]
Might be worth to do it but with a warning. It is under advanced GradleRIO either way.
