### ISSUE TITLE
Support updating vendor deps from gradle

### ISSUE THREAD

**Issue by ArchdukeTim** [wpilibsuite/GradleRIO#746]
Currently the only simple way to update vendor dependencies is through the VSCode plugin. 
It would be nice if there was a gradle task that performed the same operation comparing versions and downloading the new one if one existed

**Comment by falOn-Dev** [comment]
[THIS](https://gist.github.com/falOn-Dev/512c62e009025b3b7569b899bbef955a) is the gist I have for doing this, I'm not sure the proper way to add this into gradlerio but if anyone wants to take a crack at it feel free

**Comment by Starlight220** [comment]
#417 added the `vendordep` task for installing vendordeps; should probably integrate with that.

**Comment by spacey-sooty** [comment]
Its stored in native utils now iirc
