### ISSUE TITLE
FRC Driver station doesn't have shuffleboard by default

### ISSUE THREAD

**Issue by sparks58** [wpilibsuite/GradleRIO#75]

**Comment by firecrafty** [comment]
This isn't an issue with GradleRIO.

**Comment by JacisNonsense** [comment]
It partially is, the driverstation looks in ~/wpilib/tools for Shuffleboard and SmartDashboard, which is managed usually by the eclipse plugins. I'll look into this soon

**Comment by GaganBhat** [comment]
I just created a windows batch file that runs a few simple commands that start shuffleboard.

**Comment by JacisNonsense** [comment]
This is being fixed in 2019 since the Driver Station is changing where it looks for tool files.
